name: Go Server CI/CD

on:
  push:
    branches:
      - master # Запускать этот workflow при пушах в ветку master

jobs:
  build-and-deploy:
    name: Build and Deploy Go Server
    runs-on: ubuntu-latest # Выбор среды выполнения

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3 # Получение исходного кода из репозитория

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20 # Указание версии Go

   

    - name: Build
      run: |
        CGO_ENABLED=0 GOOS=linux go build -a -x -o myserver_new . 
      env:
        GO111MODULE: on

    - name: Copy binary to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }} # Использование секретов GitHub для хранения конфиденциальных данных
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        source: "./myserver_new" # Путь к бинарному файлу
        target: "/root/go_example/" # Путь на сервере

    - name: Restart server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          systemctl stop go_server.service # Остановка старого процесса сервера
          mv /root/go_example/myserver_new /root/go_example/myserver # Перемещение нового бинарного файла
          systemctl start go_server.service # Запуск нового процесса сервера
# systemctl status go_server.service