name: Go Server CI/CD

on:
  push:
    branches:
      - master # Запускать этот workflow при пушах в ветку master

jobs:
  build-and-deploy:
    name: Build and Deploy Go Server
    runs-on: ubuntu-latest # Выбор среды выполнения

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3 # Получение исходного кода из репозитория

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.20 # Указание версии Go

   

    - name: Build
      run: |
        CGO_ENABLED=0 GOOS=linux go build -a -x -o myserver . 
      env:
        GO111MODULE: on

    - name: Copy binary to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }} # Использование секретов GitHub для хранения конфиденциальных данных
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        source: "./myserver" # Путь к бинарному файлу
        target: "/root/go_example/" # Путь на сервере
# with:
    # host: ${{ secrets.HOST }}
    # username: ${{ secrets.USERNAME }}
    # port: ${{ secrets.PORT }}
    # key: ${{ secrets.KEY }}
    # source: "tests/a.txt,tests/b.txt"
    # target: your_server_target_folder_path


    - name: Restart server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        password: ${{ secrets.SERVER_PASSWORD }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          systemctl stop myserver.service # Остановка старого процесса сервера
          mv /path/on/server/myserver /usr/local/bin/myserver # Перемещение нового бинарного файла
          systemctl start myserver.service # Запуск нового процесса сервера
